/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoracaixaoop;

import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class frCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form frCalculadora
     */
    public frCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCaixaDigital = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNota100 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNota50 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNota20 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNota10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNota5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMoeda1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMoeda50 = new javax.swing.JTextField();
        txtMoeda25 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMoeda10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMoeda5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        txtCaixaDigital.setBackground(new java.awt.Color(255, 255, 255));
        txtCaixaDigital.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtCaixaDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaixaDigitalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa digital");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculadora Caixa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaixaDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCaixaDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtNota100.setBackground(new java.awt.Color(255, 255, 255));
        txtNota100.setText("0");
        txtNota100.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota100ActionPerformed(evt);
            }
        });
        txtNota100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota100KeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nota 100");

        txtNota50.setBackground(new java.awt.Color(255, 255, 255));
        txtNota50.setText("0");
        txtNota50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota50ActionPerformed(evt);
            }
        });
        txtNota50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota50KeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nota 50");

        txtNota20.setBackground(new java.awt.Color(255, 255, 255));
        txtNota20.setText("0");
        txtNota20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota20ActionPerformed(evt);
            }
        });
        txtNota20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota20KeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nota 20");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nota 10");

        txtNota10.setBackground(new java.awt.Color(255, 255, 255));
        txtNota10.setText("0");
        txtNota10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota10ActionPerformed(evt);
            }
        });
        txtNota10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota10KeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nota 5");

        txtNota5.setBackground(new java.awt.Color(255, 255, 255));
        txtNota5.setText("0");
        txtNota5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota5ActionPerformed(evt);
            }
        });
        txtNota5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota5KeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nota 2");

        txtNota2.setBackground(new java.awt.Color(255, 255, 255));
        txtNota2.setText("0");
        txtNota2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });
        txtNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota2KeyTyped(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Moeda 1");

        txtMoeda1.setBackground(new java.awt.Color(255, 255, 255));
        txtMoeda1.setText("0");
        txtMoeda1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtMoeda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoeda1ActionPerformed(evt);
            }
        });
        txtMoeda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoeda1KeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Moeda 50");

        txtMoeda50.setBackground(new java.awt.Color(255, 255, 255));
        txtMoeda50.setText("0");
        txtMoeda50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtMoeda50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoeda50ActionPerformed(evt);
            }
        });
        txtMoeda50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoeda50KeyTyped(evt);
            }
        });

        txtMoeda25.setBackground(new java.awt.Color(255, 255, 255));
        txtMoeda25.setText("0");
        txtMoeda25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtMoeda25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoeda25ActionPerformed(evt);
            }
        });
        txtMoeda25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoeda25KeyTyped(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Moeda 25");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Moeda 10");

        txtMoeda10.setBackground(new java.awt.Color(255, 255, 255));
        txtMoeda10.setText("0");
        txtMoeda10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtMoeda10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoeda10ActionPerformed(evt);
            }
        });
        txtMoeda10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoeda10KeyTyped(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Moeda 5");

        txtMoeda5.setBackground(new java.awt.Color(255, 255, 255));
        txtMoeda5.setText("0");
        txtMoeda5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtMoeda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoeda5ActionPerformed(evt);
            }
        });
        txtMoeda5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoeda5KeyTyped(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setRows(5);
        txtResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jScrollPane1.setViewportView(txtResultado);

        btnCalcular.setBackground(new java.awt.Color(51, 255, 204));
        btnCalcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 204), 5, true));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNota50)
                                    .addComponent(txtNota100)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNota20)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMoeda1)
                                        .addComponent(txtMoeda50, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMoeda25)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNota10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoeda10)
                                    .addComponent(txtMoeda5)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNota2)
                            .addComponent(txtNota5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtNota50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNota20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMoeda25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNota10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMoeda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoeda50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoeda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Caixa c = new Caixa();
    DecimalFormat f = new DecimalFormat("0.00");
    private void txtNota100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota100ActionPerformed
        c.setNota100(Integer.parseInt(txtNota100.getText()));
        txtNota50.requestFocus();
    }//GEN-LAST:event_txtNota100ActionPerformed

    private void txtNota50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota50ActionPerformed
        c.setNota50(Integer.parseInt(txtNota50.getText()));
        txtNota20.requestFocus();
    }//GEN-LAST:event_txtNota50ActionPerformed

    private void txtNota20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota20ActionPerformed
        c.setNota20(Integer.parseInt(txtNota20.getText()));
        txtNota10.requestFocus();
    }//GEN-LAST:event_txtNota20ActionPerformed

    private void txtNota10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota10ActionPerformed
        c.setNota10(Integer.parseInt(txtNota10.getText()));
        txtNota5.requestFocus();
    }//GEN-LAST:event_txtNota10ActionPerformed

    private void txtNota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota5ActionPerformed
        c.setNota5(Integer.parseInt(txtNota5.getText()));
        txtNota2.requestFocus();
    }//GEN-LAST:event_txtNota5ActionPerformed

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        c.setNota2(Integer.parseInt(txtNota2.getText()));
        txtMoeda1.requestFocus();
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtMoeda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoeda1ActionPerformed
        c.setMoeda1(Integer.parseInt(txtMoeda1.getText()));
        txtMoeda50.requestFocus();
    }//GEN-LAST:event_txtMoeda1ActionPerformed

    private void txtMoeda50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoeda50ActionPerformed
        c.setMoeda50(Integer.parseInt(txtMoeda50.getText()));
        txtMoeda25.requestFocus();
    }//GEN-LAST:event_txtMoeda50ActionPerformed

    private void txtMoeda25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoeda25ActionPerformed
        c.setMoeda25(Integer.parseInt(txtMoeda25.getText()));
        txtMoeda10.requestFocus();
    }//GEN-LAST:event_txtMoeda25ActionPerformed

    private void txtMoeda10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoeda10ActionPerformed
        c.setMoeda10(Integer.parseInt(txtMoeda10.getText()));
        txtMoeda5.requestFocus();
    }//GEN-LAST:event_txtMoeda10ActionPerformed

    private void txtMoeda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoeda5ActionPerformed
        c.setMoeda5(Integer.parseInt(txtMoeda5.getText()));
        btnCalcular.requestFocus();
    }//GEN-LAST:event_txtMoeda5ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtNota100.getText().equals("") || txtNota50.getText().equals("") || txtNota20.getText().equals("") || txtNota10.getText().equals("") || txtNota5.getText().equals("") || txtNota2.getText().equals("") || txtMoeda1.getText().equals("") || txtMoeda50.getText().equals("") || txtMoeda25.getText().equals("") || txtMoeda10.getText().equals("") || txtMoeda5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "um dos parametros esta vazio.");
        } else if (txtCaixaDigital.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Parametro 'caixa digital' vazio ");
        } else {
            c.setCaixaDigital(Double.parseDouble(txtCaixaDigital.getText().replace(",",".")));
            c.setNota100(Integer.parseInt(txtNota100.getText()));
            c.setNota50(Integer.parseInt(txtNota50.getText()));
            c.setNota20(Integer.parseInt(txtNota20.getText()));
            c.setNota10(Integer.parseInt(txtNota10.getText()));
            c.setNota5(Integer.parseInt(txtNota5.getText()));
            c.setNota2(Integer.parseInt(txtNota2.getText()));
            c.setMoeda1(Integer.parseInt(txtMoeda1.getText()));
            c.setMoeda50(Integer.parseInt(txtMoeda50.getText()));
            c.setMoeda25(Integer.parseInt(txtMoeda25.getText()));
            c.setMoeda10(Integer.parseInt(txtMoeda10.getText()));
            c.setMoeda5(Integer.parseInt(txtMoeda5.getText()));
            txtResultado.setText("Resultado: "
                    + "\nCaixa Digital: " + f.format(c.getCaixaDigital())
                    + "\nCaixa fisico: " + f.format(c.calcularTotal())
                    + "\nDiferença: " + c.calcularDiferenca()
                    + "\n"
                    + "\nNota 100: " + f.format(c.getNota100()) + "     Moeda 1: " + f.format(c.getMoeda1())
                    + "\nNota 50: " + f.format(c.getNota50()) + "       Moeda 50: " + f.format(c.getMoeda50())
                    + "\nNota 20: " + f.format(c.getNota20()) + "       Moeda 25: " + f.format(c.getMoeda25())
                    + "\nNota 10: " + f.format(c.getNota10()) + "       Moeda 10: " + f.format(c.getMoeda10())
                    + "\nNota 5: " + f.format(c.getNota5()) + "         Moeda 5: " + f.format(c.getMoeda5())
                    + "\nNota 2: " + f.format(c.getNota2()));
            SimpleDateFormat d = new SimpleDateFormat("MM-dd_HH-mm");

        try (FileWriter pasta = new FileWriter("C:\\Users\\Cliente\\OneDrive - kwamenkrumahacademy.org\\Desktop\\Caixa\\" + d.format(new Date()) + ".txt")) {
            pasta.write("------------------------------------------------------\r\n");
            pasta.write("valor total do caixa fisico: " + f.format(c.calcularTotal()) + "\r\n");
            pasta.write("Valor total do caixa Digital: "+ c.getCaixaDigital() + "\r\n");
            pasta.write("Diferença: "+ c.calcularDiferenca() + "\r\n");
            pasta.write("------------------------------------------------------\r\n");
            pasta.write("notas de R$100: " + c.getNota100() + "\r\n");
            pasta.write("notas de R$50: " + c.getNota50() + "\r\n");
            pasta.write("notas de R$20: " + c.getNota20() + "\r\n");
            pasta.write("notas de R$10: " + c.getNota10() + "\r\n");
            pasta.write("notas de R$5: " + c.getNota5() + "\r\n");
            pasta.write("notas de R$2: " + c.getNota2() + "\r\n");
            pasta.write("moedas de R$1: " + c.getMoeda1() + "\r\n");
            pasta.write("moedas de R$0.5: " + c.getMoeda50() + "\r\n");
            pasta.write("moedas de R$0.25: " + c.getMoeda25() + "\r\n");
            pasta.write("moedas de R$0.10: " + c.getMoeda10() + "\r\n");
            pasta.write("moedas de R$0.05: " + c.getMoeda5() + "\r\n");
            pasta.write("------------------------------------------------------\r\n");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "houve um erro ao salvar.");
        }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtCaixaDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaixaDigitalActionPerformed
        c.setCaixaDigital(Double.parseDouble(txtCaixaDigital.getText().replace(",", ".")));
        txtNota100.requestFocus();
    }//GEN-LAST:event_txtCaixaDigitalActionPerformed

    private void txtNota100KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota100KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota100KeyTyped

    private void txtNota50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota50KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota50KeyTyped

    private void txtNota20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota20KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota20KeyTyped

    private void txtNota10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota10KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota10KeyTyped

    private void txtNota5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota5KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota5KeyTyped

    private void txtNota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota2KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota2KeyTyped

    private void txtMoeda1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoeda1KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMoeda1KeyTyped

    private void txtMoeda50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoeda50KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMoeda50KeyTyped

    private void txtMoeda25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoeda25KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMoeda25KeyTyped

    private void txtMoeda10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoeda10KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMoeda10KeyTyped

    private void txtMoeda5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoeda5KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMoeda5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCaixaDigital;
    private javax.swing.JTextField txtMoeda1;
    private javax.swing.JTextField txtMoeda10;
    private javax.swing.JTextField txtMoeda25;
    private javax.swing.JTextField txtMoeda5;
    private javax.swing.JTextField txtMoeda50;
    private javax.swing.JTextField txtNota10;
    private javax.swing.JTextField txtNota100;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota20;
    private javax.swing.JTextField txtNota5;
    private javax.swing.JTextField txtNota50;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
